# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plant_happy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("plant_happy.proto", :syntax => :proto3) do
    add_message "WateringSchedule" do
      optional :id, :int64, 1
      optional :frequency, :string, 2
      optional :repeating_days, :int32, 3
    end
    add_message "Plant" do
      optional :id, :int64, 1
      optional :scientific_name, :string, 2
      optional :common_name, :string, 3
      optional :watering_schedule, :message, 4, "WateringSchedule"
    end
    add_message "Collection" do
      optional :id, :int64, 1
      repeated :plants, :message, 2, "Plant"
    end
    add_message "PlantRequest" do
      optional :id, :int64, 1
    end
    add_message "CollectionRequest" do
      optional :id, :int64, 1
    end
  end
end

WateringSchedule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WateringSchedule").msgclass
Plant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Plant").msgclass
Collection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Collection").msgclass
PlantRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PlantRequest").msgclass
CollectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CollectionRequest").msgclass
